; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
extra_scripts = pre:scripts/patch_wire_buffer.py
build_flags =
	-D BUFFER_LENGTH=128
	-D TWI_BUFFER_LENGTH=128
	-D SOFTWAREWIRE_BUFSIZE=64
lib_deps =
	testato/SoftwareWire@^1.6.0
build_src_filter = 
	+<main.cpp>
	+<SMH_01B01.cpp>
	+<protocol.cpp>
	+<OMRON_D6T.cpp>
	+<test_MLX90640.cpp>
monitor_speed = 921600

[env:megaatmega2560_dump]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_src_filter =
	-<*>
	+<MLX90640_EEPROM_Dump.cpp>
monitor_speed = 921600
