# Auto-generated by scripts/calibration_research_pipeline.py.
# Contains only best_by_val-selected winning calibration models.

from __future__ import annotations

import math


inf = math.inf
CALIB_SELECTION_RULE = 'best_by_val'
CALIB_PROFILES = {'d6t': {'per_distance_profiles': {'15': {'coefficients': [12.819213085528455,
                                                           0.7772661159178934,
                                                           0.0005567221180503568,
                                                           -1.0023986684606843],
                                          'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                          'features': ['raw', 'raw_sq', 'delta_temp'],
                                          'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                          'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                          'target_mode': 'predict_absolute'},
                                   '25': {'coefficients': [14.468530773232686, 0.952946735867173],
                                          'feature_names_in': ['raw'],
                                          'features': ['raw'],
                                          'model_name': 'Model_1_Global',
                                          'powers': [[0], [1]],
                                          'target_mode': 'predict_absolute'},
                                   '30': {'coefficients': [-14.079410268464011,
                                                           1.5972079489764348,
                                                           -0.0018557260408267329,
                                                           -3.6247867410312784],
                                          'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                          'features': ['raw', 'raw_sq', 'delta_temp'],
                                          'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                          'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                          'target_mode': 'predict_absolute'}},
         'target_mode': 'predict_absolute'},
 'mlx90640': {'per_distance_profiles': {'15': {'coefficients': [-1.6927090624899295,
                                                                0.9309671127976281,
                                                                -0.7159658745103439],
                                               'feature_names_in': ['raw', 'delta_temp'],
                                               'features': ['raw', 'delta_temp'],
                                               'model_name': 'Model_5_PerDistance_Linear_Delta',
                                               'powers': [[0], [1, 0], [0, 1]],
                                               'target_mode': 'predict_absolute'},
                                        '20': {'coefficients': [1.266164061919033, 0.9511226941796209],
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_1_Global',
                                               'powers': [[0], [1]],
                                               'target_mode': 'predict_absolute'},
                                        '25': {'bin_models': {'120_160': {'coefficients': [-0.0917267497149503,
                                                                                           0.9985760312674372],
                                                                          'hi': 160.0,
                                                                          'lo': 120.0,
                                                                          'rows': 498},
                                                              '160_200': {'coefficients': [3.2652329370465902,
                                                                                           0.9773806188652959],
                                                                          'hi': 200.0,
                                                                          'lo': 160.0,
                                                                          'rows': 389},
                                                              '40_80': {'coefficients': [-3.466296831436103,
                                                                                         1.0215318123020547],
                                                                        'hi': 80.0,
                                                                        'lo': 40.0,
                                                                        'rows': 596},
                                                              '80_120': {'coefficients': [-3.180033131800422,
                                                                                          1.021478740251853],
                                                                         'hi': 120.0,
                                                                         'lo': 80.0,
                                                                         'rows': 853},
                                                              'gt200': {'coefficients': [12.076425250453541,
                                                                                         0.9309081321595326],
                                                                        'hi': inf,
                                                                        'lo': 200.0,
                                                                        'rows': 433},
                                                              'lt40': {'coefficients': [-5.060767334893384,
                                                                                        1.1153261380175281],
                                                                       'hi': 40.0,
                                                                       'lo': -inf,
                                                                       'rows': 164}},
                                               'fallback_profile': {'coefficients': [-0.7525046858799088,
                                                                                     0.9944247383900023],
                                                                    'feature_names_in': ['raw'],
                                                                    'features': ['raw'],
                                                                    'model_name': 'Model_2_PerDistance_Linear',
                                                                    'powers': [[0], [1]],
                                                                    'target_mode': 'predict_absolute'},
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_4_PerDistance_Bin',
                                               'target_mode': 'predict_absolute'},
                                        '30': {'coefficients': [1.7322283532939429,
                                                                0.9796416635657176,
                                                                -15.183504188820114],
                                               'feature_names_in': ['raw', 'delta_temp'],
                                               'features': ['raw', 'delta_temp'],
                                               'model_name': 'Model_5_PerDistance_Linear_Delta',
                                               'powers': [[0], [1, 0], [0, 1]],
                                               'target_mode': 'predict_absolute'}},
              'target_mode': 'predict_absolute'},
 'smh01b01': {'per_distance_profiles': {'15': {'coefficients': [3.664387969251325,
                                                                0.9336409576697788,
                                                                -0.9644904579973832],
                                               'feature_names_in': ['raw', 'delta_temp'],
                                               'features': ['raw', 'delta_temp'],
                                               'model_name': 'Model_5_PerDistance_Linear_Delta',
                                               'powers': [[0], [1, 0], [0, 1]],
                                               'target_mode': 'predict_absolute'},
                                        '25': {'coefficients': [6.712047675419744, 0.9642395887824227],
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_1_Global',
                                               'powers': [[0], [1]],
                                               'target_mode': 'predict_absolute'},
                                        '30': {'coefficients': [-3.4496523873282046,
                                                                1.1811600080861462,
                                                                -0.0005685600541800451,
                                                                -9.589364556777998],
                                               'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                               'features': ['raw', 'raw_sq', 'delta_temp'],
                                               'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                               'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                               'target_mode': 'predict_absolute'}},
              'target_mode': 'predict_absolute'}}


def _distance_key(distance_cm):
    if distance_cm is None:
        return None
    try:
        return str(int(float(distance_cm)))
    except (TypeError, ValueError):
        return None


def _linear(profile, values):
    result = float(profile["coefficients"][0])
    for coeff, value in zip(profile["coefficients"][1:], values):
        result += float(coeff) * float(value)
    return result


def _features(profile, raw, delta_temp=None):
    values = []
    for feature in profile.get("features", ["raw"]):
        if feature == "raw":
            values.append(float(raw))
        elif feature == "raw_sq":
            values.append(float(raw) ** 2)
        elif feature == "delta_temp":
            values.append(0.0 if delta_temp is None else float(delta_temp))
        else:
            raise ValueError(f"unsupported feature {feature}")
    return values


def _predict_profile(profile, raw, delta_temp=None):
    if "bin_models" in profile:
        ref = float(raw)
        for info in profile.get("bin_models", {}).values():
            if ref >= float(info["lo"]) and ref < float(info["hi"]):
                return _linear({"coefficients": info["coefficients"]}, [raw])
        return _predict_profile(profile["fallback_profile"], raw, delta_temp)
    return _linear(profile, _features(profile, raw, delta_temp))


def _active_profile(sensor_name, distance_cm):
    sensor = CALIB_PROFILES.get(sensor_name)
    if sensor is None:
        return None
    return sensor.get("per_distance_profiles", {}).get(_distance_key(distance_cm))


def calibrate(sensor_name, raw_value, distance_cm=None, direction=None, reference_temp=None, delta_temp=None):
    try:
        raw = float(raw_value)
    except (TypeError, ValueError):
        return raw_value
    if not math.isfinite(raw):
        return raw
    profile = _active_profile(sensor_name, distance_cm)
    if profile is None:
        return raw
    return float(_predict_profile(profile, raw, delta_temp))


def calibration_debug_info(sensor_name, raw_value, distance_cm=None, direction=None, reference_temp=None, delta_temp=None):
    final = calibrate(sensor_name, raw_value, distance_cm, direction, reference_temp, delta_temp)
    raw = raw_value
    reason = "selected_per_distance"
    profile = _active_profile(sensor_name, distance_cm)
    try:
        raw = float(raw_value)
    except (TypeError, ValueError):
        reason = "invalid_raw"
    if profile is None:
        reason = "profile_not_found" if sensor_name not in CALIB_PROFILES else "distance_not_selected_raw_fallback"
    features = list(profile.get("features", ["raw"])) if profile else ["raw"]
    try:
        values = _features(profile, raw, delta_temp) if profile else [float(raw)]
    except Exception:
        values = [float(raw)] if isinstance(raw, (int, float)) else [raw]
    raw_error = None
    calib_error = None
    if reference_temp is not None:
        try:
            ref = float(reference_temp)
            raw_error = float(raw) - ref
            calib_error = float(final) - ref
        except (TypeError, ValueError):
            raw_error = None
            calib_error = None
    return {
        "sensor_name": sensor_name,
        "raw": raw,
        "input_features": dict(zip(features, values)),
        "loaded_model_path": f"{__file__}#CALIB_PROFILES[{sensor_name!r}]",
        "feature_list": features,
        "feature_names_in": list(profile.get("feature_names_in", features)) if profile else features,
        "model_name": profile.get("model_name", "raw") if profile else "raw",
        "target_mode": profile.get("target_mode", "predict_absolute") if profile else "predict_absolute",
        "predicted_value": final,
        "final_calib": final,
        "distance_cm": distance_cm,
        "direction": direction,
        "raw_error": raw_error,
        "calib_error": calib_error,
        "selection_rule": CALIB_SELECTION_RULE,
        "reason": reason,
    }
