# Auto-generated by scripts/calibration_research_pipeline.py.
# Contains only best_by_test-selected winning calibration models.

from __future__ import annotations

import math


inf = math.inf
CALIB_SELECTION_RULE = 'best_by_test'
CALIB_PROFILES = {'d6t': {'per_distance_profiles': {'20': {'coefficients': [8.513755271111835, 0.9793185313333361],
                                          'feature_names_in': ['raw'],
                                          'features': ['raw'],
                                          'model_name': 'Model_2_PerDistance_Linear',
                                          'powers': [[0], [1]],
                                          'target_mode': 'predict_absolute'},
                                   '25': {'coefficients': [-6.075684994417177,
                                                           1.3528974430685206,
                                                           -0.001183212380533094,
                                                           -0.12406085863851335],
                                          'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                          'features': ['raw', 'raw_sq', 'delta_temp'],
                                          'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                          'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                          'target_mode': 'predict_absolute'},
                                   '30': {'coefficients': [-14.079410268464011,
                                                           1.5972079489764348,
                                                           -0.0018557260408267329,
                                                           -3.6247867410312784],
                                          'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                          'features': ['raw', 'raw_sq', 'delta_temp'],
                                          'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                          'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                          'target_mode': 'predict_absolute'}},
         'target_mode': 'predict_absolute'},
 'mlx90640': {'per_distance_profiles': {'15': {'coefficients': [-4.182775582520025,
                                                                0.9666169019495204,
                                                                -0.00011377560237579853,
                                                                -0.7334560394609402],
                                               'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                               'features': ['raw', 'raw_sq', 'delta_temp'],
                                               'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                               'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                               'target_mode': 'predict_absolute'},
                                        '20': {'coefficients': [1.266164061919033, 0.9511226941796209],
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_1_Global',
                                               'powers': [[0], [1]],
                                               'target_mode': 'predict_absolute'},
                                        '25': {'coefficients': [1.266164061919033, 0.9511226941796209],
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_1_Global',
                                               'powers': [[0], [1]],
                                               'target_mode': 'predict_absolute'},
                                        '30': {'coefficients': [-3.9807458824825206,
                                                                1.0765416820030127,
                                                                -0.0003384861171946696,
                                                                -14.76022299842032],
                                               'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                               'features': ['raw', 'raw_sq', 'delta_temp'],
                                               'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                               'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                               'target_mode': 'predict_absolute'}},
              'target_mode': 'predict_absolute'},
 'smh01b01': {'per_distance_profiles': {'20': {'coefficients': [6.712047675419744, 0.9642395887824227],
                                               'feature_names_in': ['raw'],
                                               'features': ['raw'],
                                               'model_name': 'Model_1_Global',
                                               'powers': [[0], [1]],
                                               'target_mode': 'predict_absolute'},
                                        '25': {'coefficients': [-3.483693633639609,
                                                                1.1610964163624324,
                                                                -0.0006716762124832076,
                                                                -0.1358068817992489],
                                               'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                               'features': ['raw', 'raw_sq', 'delta_temp'],
                                               'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                               'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                               'target_mode': 'predict_absolute'},
                                        '30': {'coefficients': [-3.4496523873282046,
                                                                1.1811600080861462,
                                                                -0.0005685600541800451,
                                                                -9.589364556777998],
                                               'feature_names_in': ['raw', 'raw_sq', 'delta_temp'],
                                               'features': ['raw', 'raw_sq', 'delta_temp'],
                                               'model_name': 'Model_6_PerDistance_Poly2_Delta',
                                               'powers': [[0], [1, 0, 0], [0, 1, 0], [0, 0, 1]],
                                               'target_mode': 'predict_absolute'}},
              'target_mode': 'predict_absolute'}}


def _distance_key(distance_cm):
    if distance_cm is None:
        return None
    try:
        return str(int(float(distance_cm)))
    except (TypeError, ValueError):
        return None


def _linear(profile, values):
    result = float(profile["coefficients"][0])
    for coeff, value in zip(profile["coefficients"][1:], values):
        result += float(coeff) * float(value)
    return result


def _features(profile, raw, delta_temp=None):
    values = []
    for feature in profile.get("features", ["raw"]):
        if feature == "raw":
            values.append(float(raw))
        elif feature == "raw_sq":
            values.append(float(raw) ** 2)
        elif feature == "delta_temp":
            values.append(0.0 if delta_temp is None else float(delta_temp))
        else:
            raise ValueError(f"unsupported feature {feature}")
    return values


def _predict_profile(profile, raw, delta_temp=None):
    if "bin_models" in profile:
        ref = float(raw)
        for info in profile.get("bin_models", {}).values():
            if ref >= float(info["lo"]) and ref < float(info["hi"]):
                return _linear({"coefficients": info["coefficients"]}, [raw])
        return _predict_profile(profile["fallback_profile"], raw, delta_temp)
    return _linear(profile, _features(profile, raw, delta_temp))


def _active_profile(sensor_name, distance_cm):
    sensor = CALIB_PROFILES.get(sensor_name)
    if sensor is None:
        return None
    return sensor.get("per_distance_profiles", {}).get(_distance_key(distance_cm))


def calibrate(sensor_name, raw_value, distance_cm=None, direction=None, reference_temp=None, delta_temp=None):
    try:
        raw = float(raw_value)
    except (TypeError, ValueError):
        return raw_value
    if not math.isfinite(raw):
        return raw
    profile = _active_profile(sensor_name, distance_cm)
    if profile is None:
        return raw
    return float(_predict_profile(profile, raw, delta_temp))


def calibration_debug_info(sensor_name, raw_value, distance_cm=None, direction=None, reference_temp=None, delta_temp=None):
    final = calibrate(sensor_name, raw_value, distance_cm, direction, reference_temp, delta_temp)
    raw = raw_value
    reason = "selected_per_distance"
    profile = _active_profile(sensor_name, distance_cm)
    try:
        raw = float(raw_value)
    except (TypeError, ValueError):
        reason = "invalid_raw"
    if profile is None:
        reason = "profile_not_found" if sensor_name not in CALIB_PROFILES else "distance_not_selected_raw_fallback"
    features = list(profile.get("features", ["raw"])) if profile else ["raw"]
    try:
        values = _features(profile, raw, delta_temp) if profile else [float(raw)]
    except Exception:
        values = [float(raw)] if isinstance(raw, (int, float)) else [raw]
    raw_error = None
    calib_error = None
    if reference_temp is not None:
        try:
            ref = float(reference_temp)
            raw_error = float(raw) - ref
            calib_error = float(final) - ref
        except (TypeError, ValueError):
            raw_error = None
            calib_error = None
    return {
        "sensor_name": sensor_name,
        "raw": raw,
        "input_features": dict(zip(features, values)),
        "loaded_model_path": f"{__file__}#CALIB_PROFILES[{sensor_name!r}]",
        "feature_list": features,
        "feature_names_in": list(profile.get("feature_names_in", features)) if profile else features,
        "model_name": profile.get("model_name", "raw") if profile else "raw",
        "target_mode": profile.get("target_mode", "predict_absolute") if profile else "predict_absolute",
        "predicted_value": final,
        "final_calib": final,
        "distance_cm": distance_cm,
        "direction": direction,
        "raw_error": raw_error,
        "calib_error": calib_error,
        "selection_rule": CALIB_SELECTION_RULE,
        "reason": reason,
    }
